### ISSUE TITLE
All ROS2 galactic packages got removed from testing repository

### ISSUE THREAD

**Issue by mathias-luedtke** [osrf/infrastructure#12]
- [x] I have checked [ROS Answers](https://answers.ros.org) for similar reports and solutions.
- [x] I have checked the [ROS Status page](https://status.ros.org) and my issue is not listed there.
- [x] I have checked the [open issues](https://github.com/osrf/infrastructure/issues) for similar reports.
- [x]  This is **not** a [security issue](https://github.com/osrf/infrastructure/blob/latest/SECURITY.md) If you have a security issue to report please do so via email to <security@openrobotics.org>.

## Problem description

https://build.ros2.org/job/Grel_sync-packages-to-testing_focal_amd64/338 failed unexpectedly and removed all of ROS2 galactic packages from http://repo.ros2.org/ubuntu/testing/dists/focal/main/binary-amd64/Packages.

**Comment by ijnek** [comment]
Sounds like another instance of https://github.com/ros-infrastructure/ros_buildfarm/issues/902, with the following in the log:

```sh
06:13:47 removing 'ros-galactic-warehouse-ros-mongo' from 'focal|main|agpgme gave error GPGME:54:  Unusable secret key
```

**Comment by clalancette** [comment]
Thanks for the report.  I've now kicked the https://build.ros2.org/job/Grel_sync-packages-to-testing_focal_amd64/ job again, which succeeded this time.  The underlying issue is still there, but that is being tracked elsewhere.  I'm going to close this out, but feel free to reopen if you are still having problems.
