### ISSUE TITLE
Rolling: package 'ros-rolling-rcl' not found 

### ISSUE THREAD

**Issue by JanStaschulat** [osrf/infrastructure#5]
- [x] I have checked [ROS Answers](https://answers.ros.org) for similar reports and solutions.
- [x] I have checked the [ROS Status page](https://status.ros.org) and my issue is not listed there.
- [x] I have checked the [open issues](https://github.com/osrf/infrastructure/issues) for similar reports.
- [x] This is **not** a [security issue](https://github.com/osrf/infrastructure/blob/latest/SECURITY.md) If you have a security issue to report please do so via email to <security@openrobotics.org>.

## Problem description
Build job for rclc repository fails on Rolling at a [pull request which only updates the version and changelog](https://github.com/ros2/rclc/pull/158) 
Error message while setting up the docker container:
```
KeyError: "The cache has no package named 'ros-rolling-rcl'"
```

Output of buid job https://build.ros2.org/job/Rpr__rclc__ubuntu_focal_amd64/238/console

```
23:53:41 # BEGIN SECTION: Run Dockerfile - generating devel tasks
23:53:41 + rm -fr /home/jenkins-agent/workspace/Rpr__rclc__ubuntu_focal_amd64/docker_build_and_install
23:53:41 + rm -fr /home/jenkins-agent/workspace/Rpr__rclc__ubuntu_focal_amd64/docker_build_and_test
23:53:41 + mkdir -p /home/jenkins-agent/workspace/Rpr__rclc__ubuntu_focal_amd64/docker_build_and_install
23:53:41 + mkdir -p /home/jenkins-agent/workspace/Rpr__rclc__ubuntu_focal_amd64/docker_build_and_test
23:53:41 + docker run --rm --cidfile=/home/jenkins-agent/workspace/Rpr__rclc__ubuntu_focal_amd64/docker_generating_dockers/docker.cid -e=HOME=/home/buildfarm -e=TRAVIS= -e=ROS_BUILDFARM_PULL_REQUEST_BRANCH= -v /home/jenkins-agent/workspace/Rpr__rclc__ubuntu_focal_amd64/ros_buildfarm:/tmp/ros_buildfarm:ro -v /home/jenkins-agent/workspace/Rpr__rclc__ubuntu_focal_amd64/ws:/tmp/ws:ro -v /home/jenkins-agent/workspace/Rpr__rclc__ubuntu_focal_amd64/docker_build_and_install:/tmp/docker_build_and_install -v /home/jenkins-agent/workspace/Rpr__rclc__ubuntu_focal_amd64/docker_build_and_test:/tmp/docker_build_and_test devel_task_generation.rolling_rclc
23:53:47 reading in sources list data from /etc/ros/rosdep/sources.list.d
23:53:47 Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/osx-homebrew.yaml
23:53:47 Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/base.yaml
23:53:47 Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/python.yaml
23:53:47 Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/ruby.yaml
23:53:47 Hit https://raw.githubusercontent.com/ros/rosdistro/master/releases/fuerte.yaml
23:53:47 Query rosdistro index https://raw.githubusercontent.com/ros/rosdistro/master/index-v4.yaml
23:53:47 Skip end-of-life distro "ardent"
23:53:47 Skip end-of-life distro "bouncy"
23:53:47 Skip end-of-life distro "crystal"
23:53:47 Skip end-of-life distro "dashing"
23:53:47 Skip end-of-life distro "eloquent"
23:53:47 Add distro "foxy"
23:53:47 Add distro "galactic"
23:53:47 Skip end-of-life distro "groovy"
23:53:47 Skip end-of-life distro "hydro"
23:53:47 Skip end-of-life distro "indigo"
23:53:47 Skip end-of-life distro "jade"
23:53:47 Skip end-of-life distro "kinetic"
23:53:47 Skip end-of-life distro "lunar"
23:53:47 Add distro "melodic"
23:53:47 Add distro "noetic"
23:53:47 Add distro "rolling"
23:53:47 updated cache in /home/buildfarm/.ros/rosdep/sources.cache
23:53:47 Crawling for packages in workspace '/tmp/ws/src'
23:53:47 Found the following packages:
23:53:47   - rclc
23:53:47   - rclc_examples
23:53:47   - rclc_lifecycle
23:53:47   - rclc_parameter
23:53:47 Package maintainer emails: antoniocuadros@eprosima.com jan.staschulat@de.bosch.com pablogarrido@eprosima.com
23:53:48 Always install the following generic dependencies:
23:53:48   - build-essential
23:53:48   - python3
23:53:48   - python3-colcon-metadata
23:53:48   - python3-colcon-output
23:53:48   - python3-colcon-parallel-executor
23:53:48   - python3-colcon-ros
23:53:48   - python3-colcon-test-result
23:53:48 Identified the following build dependencies (ignoring packages available from source):
23:53:48   - ament_cmake_ros
23:53:48   - builtin_interfaces
23:53:48   - example_interfaces
23:53:48   - lifecycle_msgs
23:53:48   - rcl
23:53:48   - rcl_interfaces
23:53:48   - rcl_lifecycle
23:53:48   - rcutils
23:53:48   - rosidl_generator_c
23:53:48   - rosidl_runtime_c
23:53:48   - rosidl_typesupport_c
23:53:48   - std_msgs
23:53:48 Resolved the dependencies to the following binary packages:
23:53:48   - ros-rolling-ament-cmake-ros
23:53:48   - ros-rolling-builtin-interfaces
23:53:48   - ros-rolling-example-interfaces
23:53:48   - ros-rolling-lifecycle-msgs
23:53:48   - ros-rolling-rcl
23:53:48   - ros-rolling-rcl-interfaces
23:53:48   - ros-rolling-rcl-lifecycle
23:53:48   - ros-rolling-rcutils
23:53:48   - ros-rolling-rosidl-generator-c
23:53:48   - ros-rolling-rosidl-runtime-c
23:53:48   - ros-rolling-rosidl-typesupport-c
23:53:48   - ros-rolling-std-msgs
23:53:48 Traceback (most recent call last):
23:53:48   File "/usr/lib/python3/dist-packages/apt/cache.py", line 299, in __getitem__
23:53:48     rawpkg = self._cache[key]
23:53:48 KeyError: 'ros-rolling-rcl'
23:53:48 
23:53:48 During handling of the above exception, another exception occurred:
23:53:48 
23:53:48 Traceback (most recent call last):
23:53:48   File "/tmp/ros_buildfarm/scripts/devel/create_devel_task_generator.py", line 304, in <module>
23:53:48     main()
23:53:48   File "/tmp/ros_buildfarm/scripts/devel/create_devel_task_generator.py", line 140, in main
23:53:48     get_binary_package_versions(apt_cache, debian_pkg_names))
23:53:48   File "/tmp/ros_buildfarm/ros_buildfarm/common.py", line 175, in get_binary_package_versions
23:53:48     pkg = apt_cache[debian_pkg_name]
23:53:48   File "/usr/lib/python3/dist-packages/apt/cache.py", line 301, in __getitem__
23:53:48     raise KeyError('The cache has no package named %r' % key)
23:53:48 KeyError: "The cache has no package named 'ros-rolling-rcl'"
23:53:49 Build step 'Execute shell' marked build as failure
23:53:49 [CMakeGNU C Compiler (gcc)] Skipping execution of recorder since overall result is 'FAILURE'
23:53:49 INFO: Processing CTest-Version 3.x (default)
23:53:49 INFO: [CTest-Version 3.x (default)] - 3 test report file(s) were found with the pattern 'ws/test_results/*/Testing/*/Test.xml' relative to '/home/jenkins-agent/workspace/Rpr__rclc__ubuntu_focal_amd64' for the testing framework 'CTest-Version 3.x (default)'.
23:53:49 ERROR: Step ‘Publish xUnit test result report’ failed: Test reports were found but not all of them are new. Did all the tests run?
23:53:49   * /home/jenkins-agent/workspace/Rpr__rclc__ubuntu_focal_amd64/ws/test_results/rclc/Testing/20210723-1512/Test.xml is 2 days 15 hr old
23:53:49   * /home/jenkins-agent/workspace/Rpr__rclc__ubuntu_focal_amd64/ws/test_results/rclc_lifecycle/Testing/20210723-1512/Test.xml is 2 days 15 hr old
23:53:49   * /home/jenkins-agent/workspace/Rpr__rclc__ubuntu_focal_amd64/ws/test_results/rclc_parameter/Testing/20210723-1512/Test.xml is 2 days 15 hr old
23:53:49 
23:53:49 Setting status of 3ac73aeb5ef2fc22ab20804fa62c00d184ce094b to FAILURE with url https://build.ros2.org/job/Rpr__rclc__ubuntu_focal_amd64/238/ and message: 'Build finished. '
23:53:49 Using context: Rpr__rclc__ubuntu_focal_amd64
23:53:49 Finished: FAILURE
```

**Comment by tylerjw** [comment]
This is causing our ci jobs for rolling-testing to fail.  It was working before Friday last week.

Here is an example of one of our failed CI run: https://github.com/ros-planning/moveit2/pull/570/checks?check_run_id=3162033611

**Comment by sloretz** [comment]
Interesting, I do see `Package: ros-rolling-rcl` in http://packages.ros.org/ros2/ubuntu/dists/focal/main/binary-amd64/Packages.

I didn't find any output from `apt-get update` or `apt update` in [this log file](https://pipelines.actions.githubusercontent.com/IlMbc7bkhr2SUGCUplICGZx86nLUzreWnWD8itw15lEJjERJjl/_apis/pipelines/1/runs/1569/signedlogcontent/4?urlExpires=2021-07-26T17%3A28%3A34.4646560Z&urlSigningMethod=HMACV1&urlSignature=wT9URrfN2OiOSSp9%2BoyzjY%2Ft86x%2FcVKu9S4IRYDa3JU%3D). Is it possible the CI job has an out of date apt cache, and that's why it find the package? I grepped for `repo.ros2.org` hoping to see a line like `Hit:1 http://repo.ros2.org/ubuntu/testing bionic InRelease` to tell me if it was fetching from the main apt repo or the testing apt repo.

**Comment by jspricke** [comment]
@sloretz I think it is `ros2-testing`: `curl http://packages.ros.org/ros2-testing/ubuntu/dists/focal/main/binary-amd64/Packages | grep "^Package: ros-rolling-rclcpp"`

**Comment by sloretz** [comment]
@nuclearsandwich could this be caused by the package sync threshold being too low? It looks like [it is set at 262](https://github.com/ros2/ros_buildfarm_config/blob/302ef3ce7924b7f92b194c758ccaadc6a9114854/rolling/release-build.yaml#L19) but there are [600-ish RBin_uF64 jobs](https://build.ros2.org/view/Rbin_uF64/).

**Comment by nuclearsandwich** [comment]
Yeah, this has been raised internally as well. Unlike many of our distros we do want to allow regressions in Rolling periodically so the usual 90-ish% sync threshold isn't correct but if the threshold is low enough that we're syncing without fundamental packages like rcl then we have a problem. Raising the threshold will not resolve the current regression.

https://github.com/ros2/ros_buildfarm_config/pull/175 will switch the sync criteria to require ros_desktop to be available which should address this issue going forward. In the meantime the regressions in the build need to be resolved.

**Comment by tylerjw** [comment]
> In the meantime the regressions in the build need to be resolved.

Did rcl and rclcpp fail to build or sync?

**Comment by sloretz** [comment]
> Did rcl and rclcpp fail to build or sync?

It looks like they didn't get built because `rmw_cyclone_dds` itself failed to build: https://build.ros2.org/job/Rbin_uF64__rmw_cyclonedds_cpp__ubuntu_focal_amd64__binary/127/

**Comment by tylerjw** [comment]
Should any packages upstream (including testing that the core packages can build on top of these libraries) of core packages be required to run some sort of pre-release test before their new version is included in a sync?  I'm not sure who from Cyclone DDS should be tagged to get this fixed.  @ivanpauno you committed the last tag to that repo.

```make[1]: Leaving directory '/tmp/binarydeb/ros-rolling-rmw-cyclonedds-cpp-0.23.1'
make: *** [debian/rules:22: build] Error 2
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
E: Building failed
Traceback (most recent call last):
  File "/tmp/ros_buildfarm/ros_buildfarm/binarydeb_job.py", line 138, in build_binarydeb
    subprocess.check_call(cmd, cwd=source_dir)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['apt-src', 'build', 'ros-rolling-rmw-cyclonedds-cpp']' returned non-zero exit status 1.
# END SUBSECTION
```

**Comment by jspricke** [comment]
the actual error is:
```
CMake Error at CMakeLists.txt:55 (add_library):
  Target "rmw_cyclonedds_cpp" links to target
  "rosidl_typesupport_fastrtps_cpp::rosidl_typesupport_fastrtps_cpp" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?


CMake Error at CMakeLists.txt:55 (add_library):
  Target "rmw_cyclonedds_cpp" links to target
  "rosidl_typesupport_fastrtps_c::rosidl_typesupport_fastrtps_c" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?


CMake Error at CMakeLists.txt:55 (add_library):
  Target "rmw_cyclonedds_cpp" links to target
  "rosidl_typesupport_fastrtps_cpp::rosidl_typesupport_fastrtps_cpp" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?


CMake Error at CMakeLists.txt:55 (add_library):
  Target "rmw_cyclonedds_cpp" links to target
  "rosidl_typesupport_fastrtps_c::rosidl_typesupport_fastrtps_c" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?


CMake Error at CMakeLists.txt:55 (add_library):
  Target "rmw_cyclonedds_cpp" links to target
  "rosidl_typesupport_fastrtps_cpp::rosidl_typesupport_fastrtps_cpp" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
```

**Comment by jspricke** [comment]
I don't think this is rmw_cyclone_dds the same tag build fine in last week: https://build.ros2.org/job/Rbin_uF64__rmw_cyclonedds_cpp__ubuntu_focal_amd64__binary/122/
Diffing the build logs, there where some Ubuntu security updates and rebuilds of: ros-rolling-rosidl-generator-py, ros-rolling-rosidl-default-runtime, ros-rolling-rmw-dds-common. Will try to reproduce.

**Comment by christophebedard** [comment]
Could it be linked to this change? https://github.com/ros2/rosidl_typesupport_fastrtps/pull/73/files. It was released 4 days ago, on July 23rd.

**Comment by hidmic** [comment]
Indeed @christophebedard. Specifically, the issue is that `rosidl_export_typesupport_libraries()` was substituted by `rosidl_export_typesupport_targets()` but dependencies were not exported accordingly. Or perhaps, the dependency on `rosidl_typesupport_fastrtps_*` shouldn't have been PUBLIC to begin with. 

`rmw_cyclonedds_cpp` is currently failing to build because `rmw_dds_common`'s CMake configuration files need but lack `find_package(rosidl_typesupport_fastrtps_*)`. Verified that by downloading the `ros-rolling-rmw-dds-common_1.3.0` debian.

**Comment by hidmic** [comment]
Working on a fix, should have it released in the next couple hours. CC @nuclearsandwich.

**Comment by hidmic** [comment]
CI took forever. https://github.com/ros/rosdistro/pull/30343 is up.

**Comment by jspricke** [comment]
I was able to reproduce the problem and tried to test the proposed fix. I'm pretty sure that it does not solve the problem but it is difficult to check because the ROS2 build farm itself is not predictable.
The problem is that the build farm installs dependencies as part of the Docker image creation, which will make Docker cache the image together with the dependencies, so it is impossible to predict which dependency versions and packages are actually installed for a particular CI job. I recommend to disable Docker caching and always start with a minimal, well defined Ubuntu base system or use well established build systems like sbuild.

Details:
I started with reproducing the build error in rmw_cyclonedds_cpp with sbuild. I build the same package (v0.23.1) against packages.ros.org/ros2/ and ros2-testing/. It compiled fine in ros2 and broke with the same error as seen on the ROS2 build farm in ros2-testing/. Next I looked which installed packages differed and found ros-rolling-rmw-dds-common_1.3.0-1focal.20210723.205305_amd64.deb to trigger the problem. Downloading the source of it and compiling it locally against ros2-testing/ and using that to compile rmw_cyclonedds_cpp didn't reproduce the error. So the ROS2 build farm compiled rmw_dds_common differently then my local sbuild.
Looking at the build log: https://build.ros2.org/job/Rbin_uF64__rmw_dds_common__ubuntu_focal_amd64__binary/114/consoleFull we see a number of oddities:

- There is no log of apt-get installing packages, instead we find:
```
Step 27/30 : RUN echo "apt-src: 0.25.2" && echo "debhelper: 12.10ubuntu1" && echo "ros-rolling-ament-cmake: 1.1.4-1focal.20210506.150302" && echo "ros-rolling-ament-cmake-gmock: 1.1.4-1focal.20210506.150329" && echo "ros-rolling-ament-lint-auto: 0.11.2-1focal.20210618.172257" && echo "ros-rolling-ament-lint-common: 0.11.2-1focal.20210618.175334" && echo "ros-rolling-osrf-testing-tools-cpp: 1.4.0-1focal.20210525.145504" && echo "ros-rolling-performance-test-fixture: 0.0.7-1focal.20210618.175535" && echo "ros-rolling-rcpputils: 2.2.0-1focal.20210720.010142" && echo "ros-rolling-rcutils: 4.0.2-1focal.20210720.005737" && echo "ros-rolling-rmw: 4.0.0-1focal.20210720.010612" && echo "ros-rolling-ros-workspace: 1.0.2-1focal.20210506.144506" && echo "ros-rolling-rosidl-default-generators: 1.1.1-1focal.20210723.204510" && echo "ros-rolling-rosidl-runtime-cpp: 2.4.0-1focal.20210713.142528" && echo "ros-rolling-rosidl-typesupport-fastrtps-c: 2.0.0-1focal.20210723.203643" && echo "ros-rolling-rosidl-typesupport-fastrtps-cpp: 2.0.0-1focal.20210723.203449" && python3 -u /tmp/wrapper_scripts/apt.py update-install-clean -q -y -o Debug::pkgProblemResolver=yes apt-src debhelper ros-rolling-ament-cmake ros-rolling-ament-cmake-gmock ros-rolling-ament-lint-auto ros-rolling-ament-lint-common ros-rolling-osrf-testing-tools-cpp ros-rolling-performance-test-fixture ros-rolling-rcpputils ros-rolling-rcutils ros-rolling-rmw ros-rolling-ros-workspace ros-rolling-rosidl-default-generators ros-rolling-rosidl-runtime-cpp ros-rolling-rosidl-typesupport-fastrtps-c ros-rolling-rosidl-typesupport-fastrtps-cpp
 ---> Using cache
```

- It does mention ros-rolling-rosidl-typesupport-fastrtps-c which is not a build dependency of rmw_dds_common (it is only in the set of suggested packages).

- This non build dependency modifies the build:
```
-- Using all available rosidl_typesupport_c: rosidl_typesupport_fastrtps_c;rosidl_typesupport_introspection_c
```

And indeed, using sbuild --add-depends="ros-rolling-rosidl-typesupport-fastrtps-c, ros-rolling-rosidl-typesupport-fastrtps-cpp" produces a ros-rolling-rmw-dds-common that breaks rmw_cyclonedds_cpp.
So I compiled the new ros-rolling-rosidl-typesupport-fastrtps-c/pp packages (v2.0.1), injected them into ros-rolling-rmw-dds-common and compiled rmw_cyclonedds_cpp and it was still broken. On the other hand, adding those two dependencies directly to the rmw_cyclonedds_cpp makes it compile with the new ros-rolling-rmw-dds-common package, so we are on the right track.

I see two possibilities to go forward:

a) build a ros-rolling-rmw-dds-common without ros-rolling-rosidl-typesupport-fastrtps-c/pp installed.
b) Make sure that ros-rolling-rmw-dds-common depends on ros-rolling-rosidl-typesupport-fastrtps-c/pp. And(!) add a build dependency so the package is reproducible. This can by done by adding:

```
+  <depend>rosidl_typesupport_fastrtps_c</depend>
+  <depend>rosidl_typesupport_fastrtps_cpp</depend>
```

to the `rmw_dds_common/package.xml`. The PR in https://github.com/ros2/rosidl_typesupport_fastrtps/pull/73 does not help as it does not change the package dependencies.

Still, we have the problem that the ROS2 build farm has packages installed that are not in the build dependencies and thus influence the build.
As far as I understand Docker caching it assumes that commands are deterministic and that it can re-use a cached image instead of running the command. This is problematic in a build system where packages are built and added to the apt repository, influencing the apt-get install result. The better way would be to postpone installing dependencies until the actual build job is executed, ideally with a local apt mirror.

Thanks to @roehling for discussing and proofreading this.

**Comment by nuclearsandwich** [comment]
Thanks for the detailed investigation and clear report.

> The problem is that the build farm installs dependencies as part of the Docker image creation, which will make Docker cache the image together with the dependencies, so it is impossible to predict which dependency versions and packages are actually installed for a particular CI job. I recommend to disable Docker caching and always start with a minimal, well defined Ubuntu base system or use well established build systems like sbuild.

Docker image build times are already a significant time sink for large package rebuilds on the build farm and I would prefer not to forego optimizations like caching unless there is a clear problem with no alternative solution.

As far as I can tell from your write-up the problem has less to do with docker caching image layers and more to do with the created environment including suggested packages that are not strictly dependencies.

I do see how the presence or absence of the suggested package could depend on whether the suggested package is available in the building repository at the time the docker image was cached and the image caching can make behavior between agent hosts harder to diagnose. We don't currently leverage shared registries for docker images currently so each host builds and maintains its own docker images.
Dependency installation is managed with a generated dockerfile snippet which includes echoing the package and version numbers of each dependency, invalidating the layers of the docker cache which would be used for out-of-date dependencies. https://github.com/ros-infrastructure/ros_buildfarm/blob/master/ros_buildfarm/templates/snippet/install_dependencies.Dockerfile.em

However, this does not account for the fact that we're not invoking apt-get in a manner that may be installing suggested or recommended packages in addition to declared build dependencies. I don't see any mention of suggests or recommends in a quick search of the ros_buildfarm issue tracker.

>     * It does mention ros-rolling-rosidl-typesupport-fastrtps-c which is not a build dependency of rmw_dds_common (it is only in the set of suggested packages).

Can you share the methods you used to explore the dependency relationship here?

rmw_dds_common is declared as a member of the rosidl_interface_packages group https://github.com/ros2/rmw_dds_common/blob/master/rmw_dds_common/package.xml#L27 which means that bloom will inject dependencies on static typesupports based on the ROS 2 platform https://github.com/ros-infrastructure/bloom/blob/8e16f287a938c3a4b46683abcc7513db2458c405/bloom/generators/rosdebian.py#L134-L135

**Comment by jspricke** [comment]
> Dependency installation is managed with a generated dockerfile snippet which includes echoing the package and version numbers of each dependency, invalidating the layers of the docker cache which would be used for out-of-date dependencies. https://github.com/ros-infrastructure/ros_buildfarm/blob/master/ros_buildfarm/templates/snippet/install_dependencies.Dockerfile.em

Thanks for the explanation, sounds ok.

> Can you share the methods you used to explore the dependency relationship here?

`bloom-generate rosdebian --ros-distro rolling`

> rmw_dds_common is declared as a member of the rosidl_interface_packages group https://github.com/ros2/rmw_dds_common/blob/master/rmw_dds_common/package.xml#L27 which means that bloom will inject dependencies on static typesupports based on the ROS 2 platform https://github.com/ros-infrastructure/bloom/blob/8e16f287a938c3a4b46683abcc7513db2458c405/bloom/generators/rosdebian.py#L134-L135

Interesting, looks like this code is not used by `bloom-generate`. Looking through `bloom-release` it seems to use `git-bloom-generate` which injects the dependencies for me but only for the build. So we would need line 134/35 with `'Depends'` instead of `'BuildDepends'`

**Comment by hidmic** [comment]
Thanks for the thorough report @jspricke. I see the problem in debian builds now.

> a) build a ros-rolling-rmw-dds-common without ros-rolling-rosidl-typesupport-fastrtps-c/pp installed.

That'd render Fast RTPS (now Fast DDS) based RMW implementation unusable, as no Fast RTPS specific typesupport would get built for `rmw_dds_common` interfaces which core DDS based RMW implementations need.

> b) Make sure that ros-rolling-rmw-dds-common depends on ros-rolling-rosidl-typesupport-fastrtps-c/pp. And(!) add a build dependency so the package is reproducible.

That's probably a fair short-term solution to ensure the `'Depends'` field is populated accordingly. We'll face the same issue with every package that provides interfaces and does not explicitly list its dependencies in its `package.xml` though.

---

This behavior you're seeing is consistent with how the `rosidl` pipeline works i.e. how interfaces are built. 

Every `ament_cmake` package building ROS 2 interfaces will delegate code generation and artifact builds to other packages present in the workspace (or any of its underlays) through a form of CMake plugin registered in an external index (i.e. the `ament` index). `rosidl-typesupport-fastrtps-c` is one of those packages. 

We can (and do) force some of these packages to be present at the time of build, but if you build `rmw_dds_common` from source and say, [`rosidl_generator_java`](https://github.com/ros2-java/ros2_java/tree/main/rosidl_generator_java) happens to be around, you'll get some jars too. Which ultimately means you can't really calculate dependencies. The entire distro in which the package was built potentially is your dependency.

This has been this way for a long time. It started to fail with https://github.com/ros2/rosidl_typesupport_fastrtps/pull/73 because now CMake knows about these dependencies. We can go back to not knowing, despite how problematic that is when it comes to understanding a package dependencies (the driving use case for that PR). A true solution would require significant changes to the `rosidl` pipeline in ROS 2. There was some discussion about this in https://github.com/ros2/rosidl/issues/560.

**Comment by hidmic** [comment]
FYI @azeey. If we end up reverting https://github.com/ros2/rosidl_typesupport_fastrtps/pull/73 & co, using a binary ROS 2 distribution from a different build system like Bazel will get more complicated (we can't compute package dependencies anymore).

**Comment by nuclearsandwich** [comment]
> Interesting, looks like this code is not used by `bloom-generate`. Looking through `bloom-release` it seems to use `git-bloom-generate` which injects the dependencies for me but only for the build. So we would need line 134/35 with `'Depends'` instead of `'BuildDepends'`

The static typesupports are only injected as build dependencies by design. If it's now true that those dependencies are needed at runtime directly by the interface packages then we will have to update our injection process once that's confirmed.

I'll check bloom-generate and see if I can reproduce the lack of injection.

**Comment by nuclearsandwich** [comment]
> If we end up reverting [ros2/rosidl_typesupport_fastrtps#73](https://github.com/ros2/rosidl_typesupport_fastrtps/pull/73) & co, using a binary ROS 2 distribution from a different build system like Bazel will get more complicated (we can't compute package dependencies anymore).

@hidmic I think it makes the most sense to split this portion of the issue into ros2/ros2 as I'm planning to close this infra issue as soon as we have a decent sync into testing.

**Comment by nuclearsandwich** [comment]
Now that https://github.com/ros2/ros_buildfarm_config/pull/175 has merged there should no longer be syncs to testing that are missing critical packages. Additionally the release causing the regressions has been rolled back and the testing repository is in good condition so this issue is now resolved both in the immediate case and unlikely to occur again in the same fashion. Thanks everyone for the report, input, and discussion.
